# Generated by Django 3.2.7 on 2021-09-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=50)),
                ('brand', models.CharField(choices=[('redmi', 'Redmi'), ('samsung', 'Samsung'), ('apple', 'Apple'), ('oppo', 'Oppo'), ('vivo', 'Vivo'), ('realme', 'Realme')], max_length=50)),
                ('ram', models.IntegerField()),
                ('price', models.FloatField()),
                ('internal_storage', models.IntegerField()),
                ('battery_capacity', models.IntegerField()),
                ('sim_type', models.CharField(choices=[('single sim', 'Single Sim'), ('dual sim', 'Dual Sim')], max_length=50)),
                ('image', models.FileField(upload_to='document/')),
            ],
        ),
    ]
